### ISSUE TITLE
Disconnected from server error

### ISSUE THREAD

**Issue by DanaStanley** [raytonghk/genepiper#17]
Hi all
GenePiper installed without issues but running it from any browser gives an error - disconnected from server. When I select reload the same error appears. I do not even get to load the data.
I installed GP on windows and I can see that VM is using only a fraction of my mem and CPUs. 
Can you please help me with the error and increase the VM specs?
D

**Comment by didietkeren** [comment]
Same with me. Maybe I will try reinstall with older version of vagrant/ Vmbox.

**Comment by Leytoncito** [comment]
the same happened to me. Gene pipers installed successfully, and the link  loads correctly but trying to upload my files disconnects the server

**Comment by didietkeren** [comment]
I think the vagrantfile script should be updated,

**Comment by raytonghk** [comment]
The problem is the old version R 3.6 used which some packages cannot install and update. The new vagrantfile was update to install R 4.1. Destroy the old vagrant virtual box by vagrant destroy. Download the new vagrantfile and redo the vagrant up. Thank you for using Genepiper.
