### ISSUE TITLE
Different format with exported table from qiime2

### ISSUE THREAD

**Issue by didietkeren** [raytonghk/genepiper#4]
Hi, I found that the format that Genepiper use is different from exported table from Qiime2 pipeline. 1. 1.The feature table need a little modification on the column title (easy to do).
2.The taxonomy table need major modification (and I haven't find a way to do that as simple as the feature table mod). The qiime2 exported taxonomy table are not divide taxa grup by column, but by symbol in front of the taxa name (all in one column). 
This the taxonomy table exported from Qiime2 pipeline.
![Screenshot_2020-01-09_13-47-33](https://user-images.githubusercontent.com/31793421/72044643-e095c500-32e6-11ea-80c7-a00f5d6a6a52.png)

Is there any solutions?

Thanks.

Didit`

**Comment by raytonghk** [comment]
Hi @didietkeren. I am not familiar with Qiime2 but as I know the feature table are in biom file format. For the taxonomy table file, I make the following R script for you to convert the taxonomy table to a simple tab-delimited table and save it. You just need to indicate the taxonomy file path and assign the output file path. And we plan to add an individual module for qiime2 data import but need more information on the output files format.
`library(tidyverse)

read_tsv("Taxonomy file path") %>%
  select(-confidence) %>%
  separate(taxonomy, c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"), sep = "; ") %>%
  rowwise() %>%
  mutate_at(vars(-`#OTUID`), ~{strsplit(.x, "__")[[1]][2]}) %>%
  write_tsv("Output file path")`

**Comment by raytonghk** [comment]
Hi @didietkeren. Thank you for interested in Genepiper. I am not familiar with Qiime2 but as I know the feature table are in biom file format. For the taxonomy table file, I make the following R script for you to convert the taxonomy table to a simple tab-delimited table and save it. You just need to indicate the taxonomy file path and assign the output file path. And we plan to add an individual module for qiime2 data import but need more information on the output files format.

library(tidyverse)

read_tsv("Taxonomy file path") %>%
select(-confidence) %>%
separate(taxonomy, c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"), sep = "; ") %>%
rowwise() %>%
mutate_at(vars(-\`#OTUID\`), ~{strsplit(.x, "__")[[1]][2]}) %>%
write_tsv("Output file path")

**Comment by didietkeren** [comment]
Thanks, I'll try it.
Oh, and can't we edit/delete Projects in import menu?

**Comment by raytonghk** [comment]
@didietkeren. You can use "Filter Phyloseq" module to edit and use "Delete Phyloseq" module to delete the data.
