### ISSUE TITLE
Can't load genepiper in web browser, try to re-install genepiper but got error 

### ISSUE THREAD

**Issue by didietkeren** [raytonghk/genepiper#5]
Hi, I've already success installing Genepiper on my machine and running it without big problem. But suddenly it won't load when I call it form the web browser (not as usual).
Then i try to re-install genepiper again... then got this error message when running "vagrant up" for the first time:

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'ubuntu/trusty64' (v0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/ubuntu/trusty64
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

bsdtar: Error opening archive: Unrecognized archive format
----------------------------------------------------------------------------------------------------

Is there any solution for this error?
Thanks..

(my machine: Linux Mint 19,2, free storage space 20GB (on root and on home dir)

**Comment by raytonghk** [comment]
Hi @didietkeren. You may have updated the VirtualBox 6.1. It is the issue of vagrant that doesn't supported. The solution have to be waited for the next release of vagrant. Or you may try the solution suggested by vagrant.
[https://github.com/oracle/vagrant-boxes/issues/178#issue-536720633](url)
