### ISSUE TITLE
exporting results into  different formats and other enhancements

### ISSUE THREAD

**Issue by razz1618** [raytonghk/genepiper#8]
Hi,
Recently I came across genepiper and from its layout, it looks very user friendly and rich in features. After plotting a graph for say, a bar chart I came across two problems:
1) there is no option to change the colors of the different groups manually in bar charts.
2) The default image format is .png  There is no other option especially, EPS would have been nice for editing in Illustrator.
3)The relative abundance in bar graphs shows 0-1 as scale. what does that means, is it 0 to 1 % or 100% or some other unit?

**Comment by raytonghk** [comment]
Hi @razz1618,
Thank you for interested in GenePiper. We will consider to add colorpicker and more output options in the next update. For the relative abundance, 0 to 1 means 0% to 100%.

**Comment by razz1618** [comment]
Thanks. that will be great. waiting for next update
